### ISSUE TITLE
Mechanism to access default values

### ISSUE THREAD

**Issue by zhiweicen** [openconfig/ygot#101]
It is common for a leaf node to have a default value ([here](https://github.com/openconfig/public/blob/master/release/models/wifi/phy/openconfig-wifi-phy.yang#L135) is an example). If those nodes are unset, the current behavior is that the node is marked as unset (nil). This is not ideal as the Go code lost the information of the default value. I can think of two possible solutions to this.

1) Provide an additional API for each node to access its default value (nil if there is no default value). Or
2) Set the field to have the value of the default even if the field is unset.

Option 2) has the drawback of losing the fact when a field is purposefully unset but either implementation would be a good step forward compared with the current behavior.

**Comment by robshakir** [comment]
For option 2, do you mean that this is set when accessing the field, as well as when marshalling? IMHO, this gives us difficult user semantics. I would prefer some additional API. This could be a defaults method with each type as a receiver, it'd return a copy of the receiver type with the defaults populated if they existed.

**Comment by zhiweicen** [comment]
For option 2 I was only thinking about accessing the field, but not putting it in when marshalling may create other problems (e.g. when the JSON file is to be consumed by other parsers). I agree that Option 1) is a better choice.

PS the github renderer showed my comment about option 2) as another option (number three). I just updated the original post to avoid this.

**Comment by robshakir** [comment]
OK - so I propose we implement this per the following:

 * Implement a `ΛDefaults` method on each struct (continuing the naming based on characters that are not legal in YANG). This would return the type with the defaults populated if they were set. 
 * There is a little work to do here since goyang's `Entry` struct populates this as a `string` (see [here](https://github.com/openconfig/goyang/blob/master/pkg/yang/entry.go#L73)). We need to convert the string to the relevant schema type to return it.
 * `EmitJSON`/`ConstructJSON` would have a new flag to specify whether defaults should be included, in this case, it'd call the `ΛDefaults` method and (when the value is `nil`) use the default.

**Comment by ostromart** [comment]
How about Unmarshal? Seems like we'd want defaults there too.

**Comment by robshakir** [comment]
I don't think that Unmarshal has to handle this -- because if we're unmarshalling then we might want to know that explicitly the input data did not set this field - this would mean that we leave the field as `nil` in the case that the leaf is not present; explicitly set it to the default if it is set (as per today's implementation); and leave the handler of the struct to retrieve the default in the unset case.

Does that make sense?

**Comment by KBA07** [comment]
@robshakir: Query related to Unmarshaling of yang data.

Suppose I have a yang model
`
module dns {
	yang-version 1.1;
	namespace "urn:config:yang:interfaces"; 
	prefix "dns-config";

	import ietf-inet-types {
		prefix inet;
	}
	// import ietf-yang-types {
	// 	prefix yang;
	// }
	
	organization	"ABC";

	description	"YANG module for DNS configuration";

	revision 2021-03-03 {
		description "Initial version";
	}

	container dnsconfig {
		leaf port {
			type uint16 {
				range "0 .. 65353";
			}
			default 0;
		}
		leaf DNSFwdSelection {
			type string {
				length "1";
				pattern "[0-3]";
			}
			default "0";
		}
		
		leaf dns1 {
			type inet:ipv4-address;
			mandatory true;
		}
	}
}
`
I used this to generate the equivalent GO struct for data parsing and validation.

`
type Dnsconfig struct {
	DNSFwdSelection   *string `path:"DNSFwdSelection" module:"dns"`
	Dns1              *string `path:"dns1" module:"dns"`
	Port              *uint16 `path:"port" module:"dns"`
}
`

Now when I try to unmarshal the incoming JSON(without DNSFwdSelection, Port) against the generated go struct. Ygot will not populate default DNSFwdSelection and Port values which were mentioned in the yang file?

Also, Will this remain the same going forward as well?

Because I believe there should be a flag-based mechanism provided at the time of unmarshaling which would populate the default value in the struct with whatever was mentioned in the Yang file.

Looking forward to your response.

**Comment by robshakir** [comment]
// cc @wenovus 

Yes, that's right -- today, we would not auto-populate the YANG-specified `default` value into the struct based on the discussion above - you're right that this could be something that is flag-controlled (or controlled using an option passed to `Unmarshal`).

We would not want to change the default behaviour (I believe all the discussion above are still valid), but I do think that we might want to support the option that you suggest. We'd be happy to review a PR for this.

**Comment by KBA07** [comment]
@robshakir 

Let me dig into the code and try to provide a fix, but this might take some time since I am new to this package.

**Comment by wenovus** [comment]
Apologies for missing the discussion.

In addition to using a flag to populate default values while unmarshalling, another way this can be achieved in KBA07's example is by generating `GetOrCreateDefault` methods that populate default leaves (non-recursively), and then calling unmarshal on the struct.

However, if we want to recursively populate these default values beyond a single level of structs, then we will need a flag. So what we could do here is that while traversing a container/list value that is present in the JSON, we can populate it with the default leaf values first, and then carry on with unmarshalling (similar to the previous paragraph's approach). For JSON unmarshalling this could be done at `ytypes.makeField`.

For both these ideas, having a `ΛDefaults` will help with the implementation.

**Comment by wenovus** [comment]
I thought about this a bit more and I want to replace my last comment with the following thoughts:

I agree with Rob and zhiweicen that option 1 (in the very first comment) makes more sense. I think option 2 turns out to be similar to option 1. When you're creating a list element (e.g. `GetOrCreate`), you need a helper in order to populate its default values. While we could avoid adding a helper for all other nodes (e.g. containers) except the root struct, doing this only limits flexibility by making it difficult to populate default values for a non-root container element.

Two ways of doing option 1 are either to provide a helper that recursively populates the default fields, or to non-recursively populate the default fields. These two sub-options are similar, since for the latter we can just provide another helper `PopulateDefaults` to do the recursive population.

### Recursive
```
d := oc.NewDefaultDevice()
i := d.GetOrCreateInterface() // Recursively populates defaults
```

### Non-recursive
```
d := *oc.Device{}
i := d.GetOrCreateInterface() // Populates defaults
d.PopulateDefaults() // Recursively populates default values if the value is UNSET.
```

Both examples above need a new flag that tells `GetOrCreate` to populate the defaults instead of just instantiating an empty struct. Alternatively, we can add `GetOrCreateDefault`, which doesn't require any flags, but makes the API a bit more complex and verbose.

Both sub-options solve the marshal and unmarshal problems, since a user would can just create a default-populated `GoStruct` and do either operations as usual.

Right now I'm leaning towards the non-recursive sub-option since it doesn't needlessly populate everything, while still allowing for the recursive population of the default values if necessary. Supporting it is also a more incremental task. I think we don't even need `ΛDefaults` to make this work, and can just rely on recursively calling `GetOrCreate`.

@robshakir what do you think?

**Comment by wenovus** [comment]
Rob pointed out `ygot.BuildEmptyTree`, which looks very similar to the recursive idea above, except using a function instead of a method.

Also I might have misunderstood `ΛDefaults` above. Basically `ΛDefaults` is the non-recursive idea.

So it looks like we have a convergence of ideas, just need to select which of the two.

**Comment by robshakir** [comment]
Don't we need both? `ygot.BuildEmptyTree` does the recursion -- we'd need something that it can call at each hierarchy level that knows what defaults to populate, and then subsequently populates them. `ΛDefaults` could return the field name -> default map, or the populated "empty but with defaults" struct which `BuildEmptyTree` sets the container to.

**Comment by wenovus** [comment]
Makes sense that the non-recursive method is always needed. Would we want to hide the non-recursive method since it might cause misuse?

**Comment by robshakir** [comment]
Essentially that is what the greek-prefixed methods are -- non-obviously public methods that we need to be public so that we can call them from ygot on the generated code. Is there another method of hiding them that you're thinking of?

**Comment by wenovus** [comment]
No sounds good! I just wanted to get consensus that it didn't make sense to expose a non-recursive method.

So one proposal would be:
* Add `ΛDefault()` to every `GoStruct` that returns a default version of struct without modifying the existing one.
* Add `ygot.BuildDefaultTree` to recursively instantiate any nil containers and populate them with their default values by calling `ΛDefault()` on each field (if it exists).

```go
// Default device
d := *oc.Device{}
ygot.BuildDefaultTree(d)

// Default interface
i := d.GetOrCreateInterface("foo")
ygot.BuildDefaultTree(i)

// This pattern might help with converting existing code:
i2 := d.GetOrCreateInterface("bar")
i2.Mtu = ygot.Uint(1500)
iDef := *oc.Interface{}
ygot.BuildDefaultTree(iDef)
i2, err := ygot.MergeStructs(iDef, i2)

func (*S) ΛDefault() *S {
  s := &S{}
  s.Enabled = ygot.Bool(true)
  ...
  return s
}
```

If needed, we can add a helper method `PopulateDefaults` for each `GoStruct`. Its downside is that it returns an error.
```go
// Default device
d := *oc.Device{}
err := d.PopulateDefaults()

// Default interface
i := d.GetOrCreateInterface("foo")
err = i.PopulateDefaults()

// This pattern might help with converting existing code:
i2 := d.GetOrCreateInterface("bar")
i2.Mtu = ygot.Uint(1500)
err = i2.PopulateDefaults() // Recursively populate unset values with their default values.

func (s *S) PopulateDefaults err {
  def := &S{}
  ygot.BuildDefaultTree(def)
  var err error
  s, err = ygot.MergeStructs(def, s)
  return err
}
```
How does look to you?

**Comment by robshakir** [comment]
SGTM.

**Comment by wenovus** [comment]
@robshakir I want to propose a different design. The design above has an annoyance whereby `BuildDefaultTree` and `PopulateDefaults` will return an error; however, this should not be necessary. This is because `ΛDefault` doesn't return errors, and the semantics of `PopulateDefaults` means fields with defaults should only be populated when the destination struct's field is empty; therefore, no error should be necessary.

To avoid having to return an error, as well as to simplify the design, I'm thinking of generating just the following method for every `GoStruct`:
```go
func (s *Interface) PopulateDefaults() {
  if (s == nil) {
    return
  }
  ygot.BuildEmptyTree(s) // This allows PopulateDefaults to be called for all child GoStructs (containers).

  // Simple Leaves
  if (s.Enabled == nil) {
    s.Enabled = ygot.Bool(true)
  }
  ...
  // Leaf-lists NOT SUPPORTED
  // Binary
  if (s.BinaryVal == nil) {
    s.BinaryVal = Binary("abc=")
  }
  // Union
  if (s.UnionVal == nil) {
    s.UnionVal = "foo"
  }
  // Containers
  s.Aggregation.PopulateDefaults()
  ...
  // Lists
  for _, ss := s.Subinterface {
    ss.PopulateDefaults()
  }
  ...
}
```
This single interface allows for simple practical use, where lines 7 and 8 commute:
```go
1 // Default device
2 d := *oc.Device{}
3 d.PopulateDefaults()
4
5 // Default interface, but with Mtu = 1500.
6 i := d.GetOrCreateInterface("bar")
7 i.Mtu = ygot.Uint(1500)
8 i.PopulateDefaults()
```

**Comment by wenovus** [comment]
This design also has the advantage of avoiding having to implement yet another utility function using `reflect` (i.e. `BuildDefaultTree`).

**Comment by robshakir** [comment]
SGTM, let's go with this design as we discussed offline.
