### ISSUE TITLE
export model info in ygot generated file

### ISSUE THREAD

**Issue by larryleguo** [openconfig/ygot#126]
It would be nice to export model name, version number, org, in the format of gnmi.ModelData. The gnmi server needs to return model data when requested.

**Comment by robshakir** [comment]
Sure -- this is something that we can support.

I'd propose:
- Model name is taken from each `module` that the code is generated from. We would not include any `submodule`, but would include any module that was supplied and parsed.
- Version number would be the `openconfig-version` if present, otherwise revert to the `revision`.
- Organisation will be taken from `organization` in the YANG model, nil if not specified.

Does this sound reasonable?

**Comment by robshakir** [comment]
Fixed in #253.
