### ISSUE TITLE
Duplicated struct generation

### ISSUE THREAD

**Issue by ishidawataru** [openconfig/ygot#167]
When generating golang structures with the following yang model, `generator` generates two golang structs, `Top_A_C` and `Top_B_C` which corresponds to `container c` despite the fields inside them are identical.

Is it possible to suppress this duplication?

```yang
module test {
    yang-version 1;
    namespace "http://example.com";
    prefix "test";

    grouping g {
        container c {
            leaf value {
                type uint8;
            }
        }
    }

    container top {
        container a {
            uses g;
        }

        container b {
            uses g;
        }
    }

}
```

**Comment by robshakir** [comment]
ygot generates structures based on compiled data tree of the YANG model, not its logical constructs. This means that it resolves `uses` statements and includes the contents of the specified `grouping` within the struct. In your case then containers `a` and `b` - and thus the structs `Top_A` and `Top_B` - are only identical because only one `grouping` is used. If two were used, then the two would differ, and hence we couldn't generate a single struct. This approach would also be very fragile to internal refactoring of the YANG schema that would not affect the data tree structure.

Our design philosophy is that users need to know as little about YANG as possible to consume the models. Thus, I don't expect that there is a case whereby we want to generate code for `grouping` statements ever. What would the use case for this be? Could you elaborate on how it would overcome the above issues?

r.

**Comment by ishidawataru** [comment]
@robshakir Thanks for your answer.

I'm having trouble with the following model.

```yang
module test {
   yang-version 1;
   namespace "http://example.com";
   prefix "test";

   grouping g {
      container c {
          leaf value {
             type uint8;
          }
      }
   }

   container top {
      container config {
         uses g;
      }
      container state {
         uses g;
      }
   }
}
```

If I use `generator` with `-compress_paths` option, `generator` generates two structures named `Top_C` and `Top_C_` which corresponds to `/test/top/config/c` or `/test/top/state/c` but which corresponds to which is not deterministic and changes occasionally ( I think it is caused by the fact that map iteration is not ordered ).

This behavior causes trouble to the application which uses the generated go file since I need to change the structure name manually every time the naming changes.

I thought if we can use the same structure for `grouping g`, we can solve this problem.
Another solution would be adding some naming scheme or config/state structure when `-compress_paths` is used. WDYT?

**Comment by robshakir** [comment]
This layout is not valid according to the OpenConfig structure (no
containers can exist under config). This behaviour is therefore undeefined
and out of scope for path compression.

You should validate the schema against the OpenConfig style guide and
linter before expecting compress paths to work.

r.

**Comment by ishidawataru** [comment]
I see. Thanks a lot for your answer.
