### ISSUE TITLE
uint64 fields being mapped to string

### ISSUE THREAD

**Issue by SVenky** [openconfig/ygot#266]
uint64 fields are generated as a string and hence when we try to use the JSON input data which will have a number for the field it throws an error. uint64 could be mapped to float64?

**Comment by robshakir** [comment]
Hi,

Please can you clarify where you're seeing `uint64` as `string`? The only place that ygot will do this is mapping to RFC7951 JSON -- since in this case, RFC7951 specifies that 64-bit integers and float64 are mapped to strings. In generated Go and protobufs the uint64 types are used.

Please can you provide additional details?

Thanks,
r.

**Comment by robshakir** [comment]
Thanks for the updates. I edited your message just to make the diff readable (you can do this by prefixing with '```diff' and suffixing with '```').

I'm a little confused here -- we would expect that in serialised JSON then a `uint64` is represented as a string -- is the JSON that you're using something that ygot has produced? The change that you've made means that `uint64` would rather be represented as a float, which isn't compliant with 7951. We also seem to handle this case cleanly [here](https://github.com/openconfig/ygot/blob/master/ygot/render.go#L1049).

Note that `Unmarshal` **only** supports RFC7951 format JSON.

Can you provide a test case to reproduce this perhaps?

Thanks,
r.

**Comment by SVenky** [comment]
Issue with the JSON data source used. working fine otherwise consistently. Closing the issue. thanks for the support rob!
