### ISSUE TITLE
Question: YANGEmpty code generation

### ISSUE THREAD

**Issue by idefixcert** [openconfig/ygot#283]
To be honest, I did't get the point why we need YANGEmpty, so maybe my question is silly:
```
type OpenconfigInterfaces_Interfaces_Interface_RoutedVlan_Ipv6_Neighbors_Neighbor_State struct {
...
	IsRouter         YANGEmpty                                                                                          `path:"is-router" module:"openconfig-if-ip"`
...
}
```
Since in the generated code the YANGEmpty field is not a pointer so I can't assign nil.
Is that an error or is that "works as designed"?
If so, should nil be false?

Regards Chris

**Comment by robshakir** [comment]
Hi Chris,

Apologies, started writing a reply to this and then lost the tab somewhere.

In YANG `empty` is a type that is either present, or not. It's easiest to understand it in XML, where we might hvae:

```xml
<state>
  <is-router />
</state>
```

`is-router` is either there, or not - i.e., it only has two states. `boolean` fields have three - unset, true, and false.

We don't make `empty` fields pointers such that we don't erroneously introduce a tri-state for them. It wouldn't be clear whether explicitly setting an `empty` to false would mean that it should be serialised or not, for example. We make `YANGEmpty` a derived type of bool in Go, such that we can recognise it and serialise it differently -- since in JSON it is serialised as `is-router: [null]` rather than true/false.

Cheers,
r.

**Comment by wenovus** [comment]
I'm not quite understanding why you're converting a `YANGEmpty` to string for  Get/Set. However you can cast it to a bool using `bool(v)`
