### ISSUE TITLE
If key of a list is binary, the generated map has invalid keytype "Binary"

### ISSUE THREAD

**Issue by soumiksamanta** [openconfig/ygot#426]
```
module binary-map-key {
    yang-version "1";

    // namespace
    namespace "urn:binary-map-key";
    prefix "binary-map-key";

    grouping binary-map-keys-list {
        list tests {
            key "key";
            leaf key {
                type binary {
                    length "1..64";
                }
            }
            leaf name {
                type string;
            }
            leaf value {
                type string;
            }
        }
    }

    grouping binary-map-key-top {
        container testdata {
            uses binary-map-keys-list;
        }
    }
    uses binary-map-key-top;
}

```
The above yang generates the following go code

```
// BinaryMapKey_Testdata represents the /binary-map-key/testdata YANG schema element.
type BinaryMapKey_Testdata struct {
	Tests	map[Binary]*BinaryMapKey_Testdata_Tests	`path:"tests" module:"binary-map-key"`
}
```

Building the generated code, results in an error
`invalid map key type Binary`

Though golang does not support byte slices to be used as keys of a map, a valid yang file can have a keyed list with binary key.

Any plans to support this?

**Comment by robshakir** [comment]
Thanks for reporting this issue.

What would your expected generated code for this YANG construct be? It seems to me that we have a few options:

* Convert the `Binary` type to be an array rather than a slice. This would mean that the type becomes comparable, and thus we can make it a map key. However, this would mean that we need to synthesise an array size -- clearly, we can do this when there is a `length` restriction, but there's no implicit length that is defined in RFC7950 that we could use - so we'd end up with an arbitrary restriction, and a memory overhead because of allocating these bytes, which seems suboptimal.
* We could add a wrapper type specifically for this -- i.e., when the number of keys is 1 then we would generate a wrapper that could have equality compared - however, since a struct that just contains a single `[]byte` field also isn't comparable then we would need to make these maps a special type that had a pointer key type (i.e., we'd need to define:

   ```golang
   type MapKey struct {
       Key1 Binary
   }

  type Container {
    MapField map[*MapKey]SomeType
  }
    ```
* Not support this explicitly (i.e., not generate code that doesn't compile). We should do this at least until we have a decided direction for this type.

There may be some other options that I haven't thought of here, so your input would be appreciated. @wenovus -- would be interested in your thoughts too.

Cheers,
r.

**Comment by soumiksamanta** [comment]
@wenovus At least now the generator code will fail. Thanks
