### ISSUE TITLE
Remove protobuf unused imports automatically

### ISSUE THREAD

**Issue by robshakir** [openconfig/ygot#432]
`ygen` generated protobufs may have unused `ywrapper`, or `yext` imports.  In future versions of `protoc`, this may be considered an error. `ygen` should remove these imports automatically.

**Comment by wenovus** [comment]
There is the option to use `prototools format`, but it looks like it's going to be deprecated and the new formatter isn't yet available, and apparently it can even corrupt the file: https://docs.buf.build/how-to/migrate-from-prototool/#prototool-pros

So I think I'm in favour of just adding logic to have `ygen` not generate them in the first place.

**Comment by wenovus** [comment]
For implementation I'm thinking of accumulating whether `yext` or `ywrapper` is needed into bool fields in `Proto3Package`.

For `enums.proto`, `yext` is determined by the flag `AnnotateEnumNames`. As long as the package is written at all (i.e. `len(protoEnums) > 0`, then it should be written to its header. `ywrapper` should never be written for `enums.proto`.

For the other generated proto messages, `yext` is determined by the flag `AnnotateSchemaPaths` or  `AnnotateEnumNames`, and both on whether particular leaf types or enums are generated within the file. Since this is more complex, I think it makes sense to aggregate by creating bool fields for all the intermediate return types all the way up to `GenerateProto3`, which determines what header to print.

**Comment by wenovus** [comment]
For testing `enums.proto` it is sufficient to test flipping the `AnnotateEnumNames` option.

For testing other generated proto messages, will need to test flipping both options, and generating from models that generate with/without `ywrapper` types, and with/without enums.
