### ISSUE TITLE
Unmarshal into OpenconfigInterfaces_Interfaces_Interface_Subinterfaces fails

### ISSUE THREAD

**Issue by sbezverk** [openconfig/ygot#574]
After retrieving Subinterfaces with gNMI call GetRequest, the following `Unmarshal` of JSON-IETF encoded information fails with the following error:

`got float64 type for field in-octets, expect string`

Here is the code Unmarshaling data.  
```
	o := oc_interfaces_ip.OpenconfigInterfaces_Interfaces_Interface_Subinterfaces{}
	if err := oc_interfaces_ip.Unmarshal(u.GetVal().GetJsonIetfVal(), &o); err != nil {
		if err != nil {
			glog.Errorf("failed to unmarshal to Openconfig Interface struct with error: %+v", err)
			os.Exit(1)
		}
	}
```
If I use vanila json.Unmarshal into map[string]interface{}, Unmarshal works fine and the information format and the content is what would be expected.

```
Interfaces: map[subinterface:[map[index:0 openconfig-if-ip:ipv4:map[addresses:map[address:[map[ip:192.168.128.128 state:map[ip:192.168.128.128 origin:STATIC prefix-length:32]]]] state:map[counters:map[in-octets:0 in-pkts:0 out-octets:0 out-pkts:0]]] openconfig-if-ip:ipv6:map[addresses:map[address:[map[ip:2001:128:128:128::1 state:map[ip:2001:128:128:128::1 origin:STATIC prefix-length:128 status:PREFERRED]]]] state:map[counters:map[in-octets:0 in-pkts:0 out-octets:0 out-pkts:0]]]]]]
```

**Comment by robshakir** [comment]
This is a bug with the input JSON, according to RFC7951:

```
   A value of the "int64", "uint64", or "decimal64" type is represented
   as a JSON string whose content is the lexical representation of the
   corresponding YANG type as specified in Sections 9.2.1 and 9.3.1 of
   [RFC7950].
```

**Comment by sbezverk** [comment]
@robshakir how do I get around it?

**Comment by sbezverk** [comment]
@robshakir RFC talks about int64 uint64 and decimal64, nothing about `float64`, is it intentional or it is oversight? The error I pasted is for `float64`

**Comment by wenovus** [comment]
Go's representation for all numbers in marshalled JSON (i.e. `map[string]interface{}`) is float64.

**Comment by robshakir** [comment]
The `float64` number here is the `in-octets: 0` value in the input JSON. JSON numbers are `float64` by default, which is why you're seeing this.

w.r.t a workaround -- what is the source of this JSON document that you're trying to parse? The ideal would be to fix the producer, since this is something that we don't really have control over (i.e., we would need to violate RFC7951 to unmarshal this).

There is an option to introduce a type mapper into the unmarshal method -- but I'm not sure how widely applicable this is, especially if it is to deal with an implementation that is not implementing RFC7951.

**Comment by sbezverk** [comment]
@robshakir This response comes from a router, so I would need to beg the producer to change returned type to `string`
thank you.

**Comment by robshakir** [comment]
I suggest that you report this as a bug -- in the meantime you could likely fix this with something that can do a rewrite of the `float64` that are included to `uint64` in this very specific case. Unfortunately, this is hard to do generically, because you need to know what the YANG type was originally to know whether the number should be a `string` or not.

Given your values are 0 here, you could just choose to remove the `state` container that you're using.

What vendor/OS has this defect?

Thanks,
r.

**Comment by sbezverk** [comment]
@robshakir How I can exclude `state` container? Is there something in `gnmi.Path` or `gnmi.PathElem` I could use to exclude it?

**Comment by robshakir** [comment]
If you are retrieving this via gNMI `Get` then the `type` field in `GetRequest` can provide one way to do this ([proto](https://github.com/openconfig/gnmi/blob/master/proto/gnmi/gnmi.proto#L411)),

Alternatively, you could just unmarshal to `map[string]interface{}` then recursively look for the key `"state"` inside that map and set the value of such keys to `nil`.

**Comment by sbezverk** [comment]
@robshakir I already specify `Type:     gnmi.GetRequest_OPERATIONAL` in my request, but by some reason state gets in because it is a sub container of a container I am trying to get.

With regards to the workaround, that is exactly what I do now to move forward, while the issue is being investigated.

**Comment by robshakir** [comment]
Closing this issue since this is not a ygot problem. Please re-open it if there's anything else we can do.
