### ISSUE TITLE
Inquiry: Dealing with large generated files

### ISSUE THREAD

**Issue by wez470** [openconfig/ygot#996]
Hello 👋 

I'm evaluating the use of this project at my company and had a few questions I was wondering if people could help me out on. In practice the generated files are quite large. Even if I split out the structs amongst several files, the schema file generated can cause IDE issues.

I'm curious how people are generally dealing with this / what their setups are in practice. Do people just attempt to work around the large files? I noted that I can skip schema generation to avoid the issue, but that seems to lose some of the usefulness of the project. I.e. How do you now unmarshal?

Any insight would be appreciated. Thanks!

**Comment by robshakir** [comment]
Hi!

Generally, there are a few ways to deal with this. 

- Splitting into multiple files -- as you mentioned -- and choosing a number of files that limits the size of each can help. This works for some IDEs and does not for others.
- Splitting into multiple generated packages -- this can help if you don't need to handle a single "root" entity. We have discussed some enhancements to improve this approach.
- Trimming the schema to meet your requirements -- if you have a module that has `deviate not-supported` for branches of the tree that you don't care about, the overall schema size can be reduced.

I wouldn't recommend skipping the schema generation, because then as you say, unmarshalling and validation are not possible.

We're open to feedback as to different ways we might handle this. :-)

r.

**Comment by wez470** [comment]
Thanks, I'll check out those options! I don't have ideas for improvement at the moment.
